name: Build cross-mingw-w64-gdb

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install build dependencies
        run: sudo apt update && sudo apt install -y \
          git gcc g++ make patch curl xz-utils unzip libreadline-dev llvm-dev

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true

      - name: Create build and install directories
        run: |
          mkdir -p build
          mkdir -p gdb-install

      - name: Configure GDB
        working-directory: build
        run: |
          ./configure \
            --prefix=${{ github.workspace }}/gdb-install \
            --target=i686-w64-mingw32 \
            --with-system-readline \
            --disable-nls

      - name: Build GDB
        working-directory: build
        run: make -j$(nproc)

      - name: Install to local prefix
        working-directory: build
        run: make install

      - name: Cache local GDB
        uses: actions/cache@v3
        with:
          path: gdb-install
          key: gdb-msvc-${{ runner.os }}-${{ hashFiles('**/configure') }}
